name: Benchmark

on: [push, pull_request]

jobs:
  tests:
    name: Benchmark PHP Routing ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1

      - name: Quick Benchmark
        run: php quick.php

      - name: Run Symfony UrlMatcher_Benchmark
        run: vendor/bin/phpbench run benchmark/Symfony/UrlMatcher_Benchmark.php --report=short

      - name: Run Symfony CompiledUrlMatcher_Benchmark Benchmark
        run: vendor/bin/phpbench run benchmark/Symfony/CompiledUrlMatcher_Benchmark.php --report=short

      - name: Run FastRoute CharCountBased_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/CharCountBased_Benchmark.php --report=short

      - name: Run FastRoute CharCountBased_Cached_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/CharCountBased_Cached_Benchmark.php --report=short

      - name: Run FastRoute GroupCountBased_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/GroupCountBased_Benchmark.php --report=short

      - name: Run FastRoute GroupCountBased_Cached_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/GroupCountBased_Cached_Benchmark.php --report=short

      - name: Run FastRoute GroupPosBased_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/GroupPosBased_Benchmark.php --report=short

      - name: Run FastRoute GroupPosBased_Cached_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/GroupPosBased_Cached_Benchmark.php --report=short

      - name: Run FastRoute MarkBased_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/MarkBased_Benchmark.php --report=short

      - name: Run FastRoute MarkBased_Cached_Benchmark
        run: vendor/bin/phpbench run benchmark/FastRoute/MarkBased_Cached_Benchmark.php --report=short
